// Code generated by github.com/ecordell/optgen. DO NOT EDIT.
package config

import (
	defaults "github.com/creasty/defaults"
	helpers "github.com/ecordell/optgen/helpers"
)

type ConfigurationOption func(c *Configuration)

// NewConfigurationWithOptions creates a new Configuration with the passed in options set
func NewConfigurationWithOptions(opts ...ConfigurationOption) *Configuration {
	c := &Configuration{}
	for _, o := range opts {
		o(c)
	}
	return c
}

// NewConfigurationWithOptionsAndDefaults creates a new Configuration with the passed in options set starting from the defaults
func NewConfigurationWithOptionsAndDefaults(opts ...ConfigurationOption) *Configuration {
	c := &Configuration{}
	defaults.MustSet(c)
	for _, o := range opts {
		o(c)
	}
	return c
}

// ToOption returns a new ConfigurationOption that sets the values from the passed in Configuration
func (c *Configuration) ToOption() ConfigurationOption {
	return func(to *Configuration) {
		to.Server = c.Server
		to.Agent = c.Agent
		to.Auth = c.Auth
		to.Console = c.Console
		to.LogFormat = c.LogFormat
		to.LogLevel = c.LogLevel
	}
}

// DebugMap returns a map form of Configuration for debugging
func (c *Configuration) DebugMap() map[string]any {
	debugMap := map[string]any{}
	debugMap["Server"] = helpers.DebugValue(c.Server, false)
	debugMap["Agent"] = helpers.DebugValue(c.Agent, false)
	debugMap["Auth"] = helpers.DebugValue(c.Auth, false)
	debugMap["Console"] = helpers.DebugValue(c.Console, false)
	debugMap["LogFormat"] = helpers.DebugValue(c.LogFormat, false)
	debugMap["LogLevel"] = helpers.DebugValue(c.LogLevel, false)
	return debugMap
}

// ConfigurationWithOptions configures an existing Configuration with the passed in options set
func ConfigurationWithOptions(c *Configuration, opts ...ConfigurationOption) *Configuration {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithOptions configures the receiver Configuration with the passed in options set
func (c *Configuration) WithOptions(opts ...ConfigurationOption) *Configuration {
	for _, o := range opts {
		o(c)
	}
	return c
}

// WithServer returns an option that can set Server on a Configuration
func WithServer(server Server) ConfigurationOption {
	return func(c *Configuration) {
		c.Server = server
	}
}

// WithAgent returns an option that can set Agent on a Configuration
func WithAgent(agent Agent) ConfigurationOption {
	return func(c *Configuration) {
		c.Agent = agent
	}
}

// WithAuth returns an option that can set Auth on a Configuration
func WithAuth(auth Authentication) ConfigurationOption {
	return func(c *Configuration) {
		c.Auth = auth
	}
}

// WithConsole returns an option that can set Console on a Configuration
func WithConsole(console Console) ConfigurationOption {
	return func(c *Configuration) {
		c.Console = console
	}
}

// WithLogFormat returns an option that can set LogFormat on a Configuration
func WithLogFormat(logFormat string) ConfigurationOption {
	return func(c *Configuration) {
		c.LogFormat = logFormat
	}
}

// WithLogLevel returns an option that can set LogLevel on a Configuration
func WithLogLevel(logLevel string) ConfigurationOption {
	return func(c *Configuration) {
		c.LogLevel = logLevel
	}
}
